interface UserGroupListProps {
  /**
   * An endpoint url
   */
  host: string;
  /**
   * Autogenerated token
   */
  token: string;
  /**
   * An array of objects to be added to the table.
   */
  metadata?: Metadata[];
  translations?: {
    /* not impl */
  };
}
/**
 * User Group Data Structure
 */
interface UserGroupsData {
  /**
   * The user group id
   */
  id: string;
  /**
   *  The user group name
   */
  name: string;
  /**
   *  A list of users
   */
  users: string[];
  /**
   *  Metadata object supplied to extend the table
   */
  metadata: {};
}

/**
 *  The props required for the User Group Form
 */
interface UserGroupFormProps {
  /**
   *  Submit the data from the form to a HOC to create or update the data.
   */
  onSubmit: (e: any) => void;
  /**
   *  Check if the current form is on edit mode
   */
  isEditing: boolean;
  /**
   *  Prop which contains the clicked row's data
   */
  selectedUserGroup: UserGroupsData;
  /**
   *  Function to update the state on the HOC on every input change
   */
  onChange: (name: string, value: string[] | string) => void;
  /**
   * Function to close the Dialog once the cancel button is clicked.
   */
  onCancel: () => void;
  /**
   * Metadata supplied on the HOC to extend the table.
   */
  metadata: Metadata[];
}
