import SvgIcon from '@material-ui/core';

type SvgIconComponent = typeof SvgIcon;

export const Adjust: SvgIconComponent
export const Animation: SvgIconComponent
export const AreaInfo: SvgIconComponent
export const Build: SvgIconComponent
export const Calendar: SvgIconComponent
export const CalendarSetting: SvgIconComponent
export const Center: SvgIconComponent
export const Chart: SvgIconComponent
export const ClearFlag: SvgIconComponent
export const Clip: SvgIconComponent
export const ClipSelection: SvgIconComponent
export const CloudExport: SvgIconComponent
export const ColorCircle: SvgIconComponent
export const ColorLine: SvgIconComponent
export const Connections: SvgIconComponent
export const ConnectionTool: SvgIconComponent
export const CopyLink: SvgIconComponent
export const Crosshair: SvgIconComponent
export const Data: SvgIconComponent
export const DefaultView: SvgIconComponent
export const Delay: SvgIconComponent
export const Dialogue: SvgIconComponent
export const Disconnect: SvgIconComponent
export const Document: SvgIconComponent
export const Draw: SvgIconComponent
export const DrawCircle: SvgIconComponent
export const DrawDikes: SvgIconComponent
export const DrawDitches: SvgIconComponent
export const DrawPolygon: SvgIconComponent
export const DrawRectangle: SvgIconComponent
export const EditSelection: SvgIconComponent
export const Eraser: SvgIconComponent
export const Extract: SvgIconComponent
export const Feed: SvgIconComponent
export const Filter: SvgIconComponent
export const FlowChart: SvgIconComponent
export const Grade: SvgIconComponent
export const HeatMap: SvgIconComponent
export const HydrographyStation: SvgIconComponent
export const Ice: SvgIconComponent
export const LessThan: SvgIconComponent
export const MapMarker: SvgIconComponent
export const MapMarkerFilled: SvgIconComponent
export const MapMarkerFilledSmall: SvgIconComponent
export const MapMarkerSmall: SvgIconComponent
export const MapMarkerWithInitials: SvgIconComponent
export const Measure: SvgIconComponent
export const Mesh: SvgIconComponent
export const Model3D: SvgIconComponent
export const MoreThan: SvgIconComponent
export const Move: SvgIconComponent
export const MultipleChoice: SvgIconComponent
export const Navigate: SvgIconComponent
export const Nestedtools: SvgIconComponent
export const North: SvgIconComponent
export const Notification: SvgIconComponent
export const NotificationAlert: SvgIconComponent
export const Open: SvgIconComponent
export const OpenInEditor: SvgIconComponent
export const Operations: SvgIconComponent
export const Point: SvgIconComponent
export const Polygon: SvgIconComponent
export const Polylines: SvgIconComponent
export const Profile: SvgIconComponent
export const ProfileCircle: SvgIconComponent
export const Project: SvgIconComponent
export const ReleaseNotification: SvgIconComponent
export const Reorder: SvgIconComponent
export const ResultMap: SvgIconComponent
export const ReverseLinks: SvgIconComponent
export const Select: SvgIconComponent
export const SelectMultiple: SvgIconComponent
export const Send: SvgIconComponent
export const SetFlags: SvgIconComponent
export const Setting: SvgIconComponent
export const Snapping: SvgIconComponent
export const SortAlphabetically: SvgIconComponent
export const SortByAscending: SvgIconComponent
export const SortByDescending: SvgIconComponent
export const SortReverseAlphabetically: SvgIconComponent
export const Sound: SvgIconComponent
export const SpecialTools: SvgIconComponent
export const SquareMarker: SvgIconComponent
export const Temperature: SvgIconComponent
export const Text: SvgIconComponent
export const ThreeD: SvgIconComponent
export const Timeline: SvgIconComponent
export const TopView: SvgIconComponent
export const Track: SvgIconComponent
export const Turbidity: SvgIconComponent
export const TwoD: SvgIconComponent
export const Unknown: SvgIconComponent
export const Unlock: SvgIconComponent
export const UploadCloud: SvgIconComponent
export const ValueRange: SvgIconComponent
export const Variable: SvgIconComponent
export const VariableGrid: SvgIconComponent
export const Water: SvgIconComponent
export const WaterLevel: SvgIconComponent
export const Wave: SvgIconComponent
export const Waves: SvgIconComponent
export const Weather: SvgIconComponent
export const Wind: SvgIconComponent
export const WindStation: SvgIconComponent
export const ZoomToArea: SvgIconComponent