name: CI - react-components
on: 
  push:
    paths: 
      - 'packages/react-components/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use cached node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: .yarn/cache/
          key: yarnCache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarnCache-

      - name: Install dependencies
        run: yarn install
        env:
          CI: true

      - name: Lint
        run: |
          cd packages/react-components && yarn lint
        env:
          CI: true

      - name: Test
        run: cd packages/react-components && yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: cd packages/react-components && yarn build
        env:
          CI: true
